"""
- CAPITALISE FIRST LETTER OF A SENTENCE
- CAPITALISE NTH LETTER OF A SENTENCE
- 3RD WORD OF STRING
- CAPITALISE ALL WORDS IN A SENTENCE
- CONVERT STRING TO LIST
- WORDS TO STRING
- SEARCH A SPECIFIC WORD IN A STRING AND ITS NUMBER OF OCCURANCE
- LONGEST WORD IN A STRING

"""




